version: '2'
services:
    demoapp-app:
        image: demoapp
        external_links:
            - demoapp-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=demoApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demoapp-mongodb:
        extends:
            file: mongodb.yml
            service: demoapp-mongodb
