version: '2'
services:
    demoapp-mongodb:
        container_name: demoapp-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/demoApp/mongodb/:/data/db/
